DROP TABLE IF EXISTS dataraw_moviemetadata;
CREATE TABLE dataraw_moviemetadata (
	colorTEXT
  ,director_nameTEXT
  ,num_critic_for_reviewsTEXT
  ,durationTEXT
  ,director_facebook_likesTEXT
  ,actor_3_facebook_likesTEXT
  ,actor_2_nameTEXT
  ,actor_1_facebook_likesTEXT
  ,grossTEXT
  ,genresTEXT
  ,actor_1_nameTEXT
  ,movie_titleTEXT
  ,num_voted_usersTEXT
  ,cast_total_facebook_likesTEXT
  ,actor_3_nameTEXT
  ,facenumber_in_posterTEXT
  ,plot_keywordsTEXT
  ,movie_imdb_linkTEXT
  ,num_user_for_reviewsTEXT
  ,languageTEXT
  ,countryTEXT
  ,content_ratingTEXT
  ,budgetTEXT
  ,title_yearTEXT
  ,actor_2_facebook_likesTEXT
  ,imdb_scoreTEXT
  ,aspect_ratioTEXT
  ,movie_facebook_likes
);
